static var highSexDrive : String { return NSLocalizedString(LocalizableConstants.Localizable_HigHSexDrive,comment:  "") }
static var lowSexDrive : String { return NSLocalizedString(LocalizableConstants.Localizable_LowSexDrive,comment:  "") }
static var withDrawal : String { return NSLocalizedString(LocalizableConstants.Localizable_WithDraWal,comment:  "") }
static var sex : String { return NSLocalizedString(LocalizableConstants.Localizable_Sex,comment:  "") }
static var noSex : String { return NSLocalizedString(LocalizableConstants.Localizable_NoSex,comment:  "") }
static var unprotected : String { return NSLocalizedString(LocalizableConstants.Localizable_Unprotected,comment:  "") }
static var protected : String { return NSLocalizedString(LocalizableConstants.Localizable_Protected,comment:  "") }
static var cervicalMucus : String { return NSLocalizedString(LocalizableConstants.Localizable_CerviCalMuCus,comment:  "") }
static var condition : String { return NSLocalizedString(LocalizableConstants.Localizable_Condition,comment:  "") }
static var dL_Light : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_Light,comment:  "") }
static var dL_Medium : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_MeDium,comment:  "") }
static var dL_Heavy : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_Heavy,comment:  "") }
static var cervicalPositionFerning : String { return NSLocalizedString(LocalizableConstants.Localizable_CerviCalPositionFerning,comment:  "") }
static var dL_Height : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_Height,comment:  "") }
static var dL_Low : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_Low,comment:  "") }
static var dL_High : String { return NSLocalizedString(LocalizableConstants.Localizable_DL_High,comment:  "") }
static var openness : String { return NSLocalizedString(LocalizableConstants.Localizable_Openness,comment:  "") }
static var closed : String { return NSLocalizedString(LocalizableConstants.Localizable_Closed,comment:  "") }
static var slightlyOpen : String { return NSLocalizedString(LocalizableConstants.Localizable_SlightlyOpen,comment:  "") }
static var open : String { return NSLocalizedString(LocalizableConstants.Localizable_Open,comment:  "") }
static var texture : String { return NSLocalizedString(LocalizableConstants.Localizable_TexTure,comment:  "") }
static var soft : String { return NSLocalizedString(LocalizableConstants.Localizable_Soft,comment:  "") }
static var medium : String { return NSLocalizedString(LocalizableConstants.Localizable_MediuM,comment:  "") }
static var firm : String { return NSLocalizedString(LocalizableConstants.Localizable_Firm,comment:  "") }
static var aidedInsemination : String { return NSLocalizedString(LocalizableConstants.Localizable_AidedInseminAtion,comment:  "") }
static var ultrasound : String { return NSLocalizedString(LocalizableConstants.Localizable_UltrasoUnd,comment:  "") }
static var sleep : String { return NSLocalizedString(LocalizableConstants.Localizable_Sleep,comment:  "") }
static var less6Hours : String { return NSLocalizedString(LocalizableConstants.Localizable_Less6Hours,comment:  "") }
static var between6And8Hours : String { return NSLocalizedString(LocalizableConstants.Localizable_Between6And8Hours,comment:  "") }
static var between8And10Hours : String { return NSLocalizedString(LocalizableConstants.Localizable_Between8And10Hours,comment:  "") }
static var moreThan10Hours : String { return NSLocalizedString(LocalizableConstants.Localizable_MoreThan10Hours,comment:  "") }
static var kG : String { return NSLocalizedString(LocalizableConstants.Localizable_KG,comment:  "") }
static var lB : String { return NSLocalizedString(LocalizableConstants.Localizable_LB,comment:  "") }
static var kgs : String { return NSLocalizedString(LocalizableConstants.Localizable_Kgs,comment:  "") }
static var lbs : String { return NSLocalizedString(LocalizableConstants.Localizable_Lbs,comment:  "") }
static var others : String { return NSLocalizedString(LocalizableConstants.Localizable_Others,comment:  "") }
static var travel : String { return NSLocalizedString(LocalizableConstants.Localizable_Travel,comment:  "") }
static var stress : String { return NSLocalizedString(LocalizableConstants.Localizable_StreSS,comment:  "") }
static var injury : String { return NSLocalizedString(LocalizableConstants.Localizable_Injury,comment:  "") }
static var illness : String { return NSLocalizedString(LocalizableConstants.Localizable_Illness,comment:  "") }
static var athleticEvent : String { return NSLocalizedString(LocalizableConstants.Localizable_AthleticEvent,comment:  "") }
static var alcohol : String { return NSLocalizedString(LocalizableConstants.Localizable_Alcohol,comment:  "") }
static var physicalActivity : String { return NSLocalizedString(LocalizableConstants.Localizable_PhysicalActivity,comment:  "") }
static var cardio : String { return NSLocalizedString(LocalizableConstants.Localizable_Cardio,comment:  "") }
static var weightLifting : String { return NSLocalizedString(LocalizableConstants.Localizable_WeightLifting,comment:  "") }
static var spin : String { return NSLocalizedString(LocalizableConstants.Localizable_Spin,comment:  "") }
static var yoga : String { return NSLocalizedString(LocalizableConstants.Localizable_Yoga,comment:  "") }
static var stretching : String { return NSLocalizedString(LocalizableConstants.Localizable_Stretching,comment:  "") }
static var breathwork : String { return NSLocalizedString(LocalizableConstants.Localizable_Breathwork,comment:  "") }
static var durationOfExercise : String { return NSLocalizedString(LocalizableConstants.Localizable_DurationOfExercise,comment:  "") }
static var between0And15Mins : String { return NSLocalizedString(LocalizableConstants.Localizable_Between0And15Mins,comment:  "") }
static var moreThan60Mins : String { return NSLocalizedString(LocalizableConstants.Localizable_MoreThan60Mins,comment:  "") }
static var otherPhysiologicalSignals : String { return NSLocalizedString(LocalizableConstants.Localizable_OtherPhysiOlOgicalSignals,comment:  "") }
static var prenatal : String { return NSLocalizedString(LocalizableConstants.Localizable_Prenatal,comment:  "") }
static var fishOil : String { return NSLocalizedString(LocalizableConstants.Localizable_FishOil,comment:  "") }
static var probiotic : String { return NSLocalizedString(LocalizableConstants.Localizable_Probiotic,comment:  "") }
static var symptoms : String { return NSLocalizedString(LocalizableConstants.Localizable_SymptomS,comment:  "") }
static var common : String { return NSLocalizedString(LocalizableConstants.Localizable_Common,comment:  "") }
static var cravings : String { return NSLocalizedString(LocalizableConstants.Localizable_Cravings,comment:  "") }
static var appetiteDecreased : String { return NSLocalizedString(LocalizableConstants.Localizable_AppetiteDecreAsed,comment:  "") }
static var appetiteIncreased : String { return NSLocalizedString(LocalizableConstants.Localizable_AppetiteIncreAsed,comment:  "") }
static var migraine : String { return NSLocalizedString(LocalizableConstants.Localizable_Migraine,comment:  "") }
static var body : String { return NSLocalizedString(LocalizableConstants.Localizable_Body,comment:  "") }
static var pelvicPain : String { return NSLocalizedString(LocalizableConstants.Localizable_PelvicPain,comment:  "") }
static var sick : String { return NSLocalizedString(LocalizableConstants.Localizable_Sick,comment:  "") }
static var vaginalPain : String { return NSLocalizedString(LocalizableConstants.Localizable_VaginalPain,comment:  "") }
static var ovulationPain : String { return NSLocalizedString(LocalizableConstants.Localizable_OvulatiOnPain,comment:  "") }
static var painDuringSex : String { return NSLocalizedString(LocalizableConstants.Localizable_PainDuringSex,comment:  "") }
static var belly : String { return NSLocalizedString(LocalizableConstants.Localizable_Belly,comment:  "") }
static var gassy : String { return NSLocalizedString(LocalizableConstants.Localizable_Gassy,comment:  "") }
static var frequentUrination : String { return NSLocalizedString(LocalizableConstants.Localizable_FrequentUrination,comment:  "") }
static var nO : String { return NSLocalizedString(LocalizableConstants.Localizable_NO,comment:  "") }
static var mild : String { return NSLocalizedString(LocalizableConstants.Localizable_Mild,comment:  "") }
static var moderate : String { return NSLocalizedString(LocalizableConstants.Localizable_Moderate,comment:  "") }
static var severe : String { return NSLocalizedString(LocalizableConstants.Localizable_Severe,comment:  "") }
static var fertilityMedication : String { return NSLocalizedString(LocalizableConstants.Localizable_FertilityMedication,comment:  "") }
static var metformin : String { return NSLocalizedString(LocalizableConstants.Localizable_MetforMin,comment:  "") }
static var letrozole_Femara : String { return NSLocalizedString(LocalizableConstants.Localizable_LetrozoLe_Femara,comment:  "") }
static var clomipheneCitrate_Clomid : String { return NSLocalizedString(LocalizableConstants.Localizable_ClomipheneCitrate_Clomid,comment:  "") }
static var babyAspirin : String { return NSLocalizedString(LocalizableConstants.Localizable_BaByAspirin,comment:  "") }
static var prometrium_BioidenticalProgesterone : String { return NSLocalizedString(LocalizableConstants.Localizable_Prometrium_BioidenticalProgesterone,comment:  "") }
static var other : String { return NSLocalizedString(LocalizableConstants.Localizable_Other,comment:  "") }
static var antiphlogistic : String { return NSLocalizedString(LocalizableConstants.Localizable_Antiphlogistic,comment:  "") }
static var tylenolAcetaminophen : String { return NSLocalizedString(LocalizableConstants.Localizable_TylenolAceTaminophen,comment:  "") }
static var advilIbuprofen : String { return NSLocalizedString(LocalizableConstants.Localizable_AdvilIbuprofen,comment:  "") }
static var aleveNaproxen : String { return NSLocalizedString(LocalizableConstants.Localizable_AleveNAproxen,comment:  "") }
static var midol : String { return NSLocalizedString(LocalizableConstants.Localizable_Midol,comment:  "") }
static var tums : String { return NSLocalizedString(LocalizableConstants.Localizable_Tums,comment:  "") }
static var heartburnMedication : String { return NSLocalizedString(LocalizableConstants.Localizable_HeartburnMedication,comment:  "") }
static var allergyMedication : String { return NSLocalizedString(LocalizableConstants.Localizable_AllergyMedicAtion,comment:  "") }
static var mucinex : String { return NSLocalizedString(LocalizableConstants.Localizable_Mucinex,comment:  "") }
static var antibiotics : String { return NSLocalizedString(LocalizableConstants.Localizable_Antibiotics,comment:  "") }
static var coughMedicine : String { return NSLocalizedString(LocalizableConstants.Localizable_CoughMediCine,comment:  "") }
static var sleepMedicine : String { return NSLocalizedString(LocalizableConstants.Localizable_SleepMedicine,comment:  "") }
static var decongestant : String { return NSLocalizedString(LocalizableConstants.Localizable_Decongestant,comment:  "") }
static var ovidrel_HCG : String { return NSLocalizedString(LocalizableConstants.Localizable_Ovidrel_HCG,comment:  "") }
static var medroxyprogesterone_Provera : String { return NSLocalizedString(LocalizableConstants.Localizable_Medroxyprogesterone_Provera,comment:  "") }
static var miscarriageBleeding : String { return NSLocalizedString(LocalizableConstants.Localizable_MiscarriageBleeding,comment:  "") }
static var moods : String { return NSLocalizedString(LocalizableConstants.Localizable_Moods,comment:  "") }
static var goodMood : String { return NSLocalizedString(LocalizableConstants.Localizable_GoodMood,comment:  "") }
static var badMood : String { return NSLocalizedString(LocalizableConstants.Localizable_BadMood,comment:  "") }
static var weepy_Tearful : String { return NSLocalizedString(LocalizableConstants.Localizable_Weepy_Tearful,comment:  "") }
static var energetic : String { return NSLocalizedString(LocalizableConstants.Localizable_EnErgEtic,comment:  "") }
static var tired : String { return NSLocalizedString(LocalizableConstants.Localizable_Tired,comment:  "") }
static var irritable : String { return NSLocalizedString(LocalizableConstants.Localizable_IrrItable,comment:  "") }
static var anxious : String { return NSLocalizedString(LocalizableConstants.Localizable_Anxious,comment:  "") }
static var obsessiveThoughts : String { return NSLocalizedString(LocalizableConstants.Localizable_ObsessiveThOughts,comment:  "") }
static var apathetic : String { return NSLocalizedString(LocalizableConstants.Localizable_ApAthetic,comment:  "") }
static var focused : String { return NSLocalizedString(LocalizableConstants.Localizable_Focused,comment:  "") }
static var inLove : String { return NSLocalizedString(LocalizableConstants.Localizable_InLove,comment:  "") }
static var spotting : String { return NSLocalizedString(LocalizableConstants.Localizable_Spotting,comment:  "") }
static var notes : String { return NSLocalizedString(LocalizableConstants.Localizable_Notes,comment:  "") }
static var saveData : String { return NSLocalizedString(LocalizableConstants.Localizable_SaveData,comment:  "") }
static var changesDailyLogTips : String { return NSLocalizedString(LocalizableConstants.Localizable_ChangesDailyLogTips,comment:  "") }
static var noDiscard : String { return NSLocalizedString(LocalizableConstants.Localizable_NoDiscard,comment:  "") }
static var yesSave : String { return NSLocalizedString(LocalizableConstants.Localizable_YesSave,comment:  "") }
static var save : String { return NSLocalizedString(LocalizableConstants.Localizable_Save,comment:  "") }
static var done : String { return NSLocalizedString(LocalizableConstants.Localizable_Done,comment:  "") }
static var howtoGetPregnantFast : String { return NSLocalizedString(LocalizableConstants.Localizable_HowtoGetPregnantFast,comment:  "") }
static var background : String { return NSLocalizedString(LocalizableConstants.Localizable_Background,comment:  "") }
static var tip_s : String { return NSLocalizedString(LocalizableConstants.Localizable_Tip_s,comment:  "") }
static var sex : String { return NSLocalizedString(LocalizableConstants.Localizable_Sex,comment:  "") }
static var fertileWindowDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_FertileWindowDescription,comment:  "") }
static var bBT : String { return NSLocalizedString(LocalizableConstants.Localizable_BBT,comment:  "") }
static var bBTDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_BBTDescription,comment:  "") }
static var ovulationTests : String { return NSLocalizedString(LocalizableConstants.Localizable_OvulatiOnTests,comment:  "") }
static var ovulationTestsDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_OvulatiOnTestsDescriptiOn,comment:  "") }
static var cervicalMucus_CM : String { return NSLocalizedString(LocalizableConstants.Localizable_CerviCalMuCus_CM,comment:  "") }
static var cMDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_CMDesCription,comment:  "") }
static var cervicalPositionFerning : String { return NSLocalizedString(LocalizableConstants.Localizable_CerviCalPositionFerning,comment:  "") }
static var cervicalPositionFerningDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_CerviCalPositionFerningDesCription,comment:  "") }
static var sleep : String { return NSLocalizedString(LocalizableConstants.Localizable_Sleep,comment:  "") }
static var sleepDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_SleepDeScription,comment:  "") }
static var weight : String { return NSLocalizedString(LocalizableConstants.Localizable_Weight,comment:  "") }
static var weightDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_WeightDescription,comment:  "") }
static var others : String { return NSLocalizedString(LocalizableConstants.Localizable_Others,comment:  "") }
static var othersDescription : String { return NSLocalizedString(LocalizableConstants.Localizable_OthersDescriptiOn,comment:  "") }
static var learnMore : String { return NSLocalizedString(LocalizableConstants.Localizable_LearnMore,comment:  "") }
